name: Automacao Blogger Luxo

on:
  workflow_dispatch:
  schedule:
    # Executa a cada 4 horas (00:00, 04:00, 08:00, etc.)
    - cron: "0 */4 * * *"

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install google-auth
          pip install google-auth-oauthlib
          pip install google-auth-httplib2
          pip install google-api-python-client
          pip install requests
          pip install feedparser
          pip install google-genai
          pip install beautifulsoup4
          pip install lxml

      - name: Executar o Robô de Luxo
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python robo_luxo.py

      # Monitoramento independente via Healthchecks
      - name: Avisar Monitor Externo que o Robô está vivo
        if: success() # Só envia o sinal se o robô postar com sucesso
        run: curl -fsS -m 10 --retry 5 https://hc-ping.com/713c69d8-3ff9-4580-a9c7-eb104b15a6e4
