name: Automacao Blogger Luxo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install google-auth
          pip install google-auth-oauthlib
          pip install google-auth-httplib2
          pip install google-api-python-client
          pip install requests
          pip install feedparser
          pip install google-genai
          pip install beautifulsoup4
          pip install lxml

      - name: Executar robo
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: python robo_luxo.py
